development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://lofrxcgidyaxwe:1e196c4bd1a271a8d9fa10a7fdbf56cc253fe2513c634d7bab2e811d6553b916@ec2-54-235-177-183.compute-1.amazonaws.com:5432/d2egg2b5julrv7
  channel_prefix: rubberduckdebug_production
