development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  url: postgres://pvpdaqazzbiqrl:75fda4c8ce91ed1ada909168405b134fdca3d817e21609c269e9f93862397dc9@ec2-54-204-23-228.compute-1.amazonaws.com:5432/d24i4at5569i3k
  # channel_prefix: rverstraten_webshop_production
  channel_prefix: rubberduckdebug_production
